"""empty message

Revision ID: 65322f5dca1d
Revises: 
Create Date: 2022-06-04 11:07:41.777325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65322f5dca1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('car_year', sa.String(length=20), nullable=True))
    op.add_column('contact', sa.Column('car_make', sa.String(length=200), nullable=True))
    op.add_column('contact', sa.Column('car_model', sa.String(length=200), nullable=True))
    op.add_column('contact', sa.Column('car_color', sa.String(length=100), nullable=True))
    op.drop_column('contact', 'phone_number')
    op.drop_column('contact', 'address')
    op.add_column('user', sa.Column('car_make', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('car_model', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('car_year', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('car_color', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'car_color')
    op.drop_column('user', 'car_year')
    op.drop_column('user', 'car_model')
    op.drop_column('user', 'car_make')
    op.add_column('contact', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('contact', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('contact', 'car_color')
    op.drop_column('contact', 'car_model')
    op.drop_column('contact', 'car_make')
    op.drop_column('contact', 'car_year')
    # ### end Alembic commands ###
